### ISSUE TITLE
BpsConnector : RemoteException: Server not available

### ISSUE THREAD

**Issue by kleinech** [OpenTOSCA/container#27]
Provision New instance of MyTinyToDo_Bare_Docker fails with error:
```o.o.c.e.p.p.b.BpsPlanEnginePlugin        : Deploying Plan: MyTinyToDo_Bare_Docker_buildPlan.zip
o.o.c.connector.bps.BpsConnector         : Setting address
o.o.c.connector.bps.BpsConnector         : Setting login data
o.o.c.connector.bps.BpsConnector         : Logging in to BPS
o.o.c.connector.bps.BpsConnector         : RemoteException: Server not available
org.apache.axis2.AxisFault: Connection refused (Connection refused)
	at org.apache.axis2.AxisFault.makeFault(AxisFault.java:430) ~[na:na]
	at org.apache.axis2.transport.http.HTTPSender.sendViaPost(HTTPSender.java:197) ~[na:na]
 	at org.apache.axis2.transport.http.HTTPSender.send(HTTPSender.java:75) ~[na:na]
 	at org.apache.axis2.transport.http.CommonsHTTPTransportSender.writeMessageWithCommons(CommonsHTTPTransportSender.java:404) ~[na:na]
	at org.apache.axis2.transport.http.CommonsHTTPTransportSender.invoke(CommonsHTTPTransportSender.java:231) ~[na:na]
	at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:443) ~[na:na]
 	at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:406) ~[na:na]
 	at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:229) ~[na:na]
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:165) ~[na:na]
 	at org.wso2.carbon.core.services.authentication.AuthenticationAdminStub.login(AuthenticationAdminStub.java:539) ~[na:na]
 	at org.opentosca.container.connector.bps.BpsConnector.login(BpsConnector.java:453) ~[org.opentosca.container.connector.bps_1.0.0.201706291221.jar:na]
	at org.opentosca.container.connector.bps.BpsConnector.deploy(BpsConnector.java:132) ~[org.opentosca.container.connector.bps_1.0.0.201706291221.jar:na]
```

**Comment by nyuuyn** [comment]
What's your setup? 

[Please visit](https://wiredcraft.com/blog/how-we-write-our-github-issues/)

**Comment by miwurster** [comment]
You sure the Bps is running?

Kálmán Képes <notifications@github.com> schrieb am Do., 29. Juni 2017,
17:49:

**Comment by miwurster** [comment]
@kleinech Do you think we can close this issue? Seems to me that this is an OpenStack-related issue...

**Comment by kleinech** [comment]
A feature requrest for the UI showing if all OpenTOSCA components are ready (Including Bps) would be nice

**Comment by miwurster** [comment]
Yes indeed, that would be nice. Could you please open a new issue according to the new [template](https://github.com/OpenTOSCA/container/blob/master/ISSUE_TEMPLATE.md)? Thanks!
