### ISSUE TITLE
No consumers available on endpoint: Endpoint[direct://Async-WS-Callback]

### ISSUE THREAD

**Issue by aimuke** [OpenTOSCA/container#9]
Hi.

After running for a few days, contianer got an error like below. After start/stop, everything is ok.
it looks like the issue in https://issues.apache.org/jira/browse/JAMES-1026 very much. and in the page it says "upgraded to camel 2.4.0 which fixes the problem". But i found container depends on camel 2.10.4.  could you help to locate how did this happen?  Thx.

Error:
2016-09-20 17:32:59,883  DEBUG  o.o.s.p.s.s.i.p.CallbackProcessor:70           Found MessageID: ID-mano-44356-1474281956908-8-107
2016-09-20 17:32:59,887  DEBUG  org.apache.camel.processor.SendProcessor:121   >>>> Endpoint[stream://out] Exchange[Message: <sch:invokeResponse xmlns:sch="http://siserver.org/schema">         sch:MessageIDID-mano-44356-1474281956908-8-107/sch:MessageID         <networkIp>133.168.1.16</networkIp>         <isSuccess>false</isSuccess>         <status>succss</status>      /sch:invokeResponse]
2016-09-20 17:32:59,887  DEBUG  o.a.c.component.stream.StreamProducer:127      Writing as byte[]: [60, 115, 99, 104, 58, 105, 110, 118, 111, 107, 101, 82, 101, 115, 112, 111, 110, 115, 101, 32, 120, 109, 108, 110, 115, 58, 115, 99, 104, 61, 34, 104, 116, 116, 112, 58, 47, 47, 115, 105, 115, 101, 114, 118, 101, 114, 46, 111, 114, 103, 47, 115, 99, 104, 101, 109, 97, 34, 62, 32, 32, 32, 32, 32, 32, 32, 32, 32, 60, 115, 99, 104, 58, 77, 101, 115, 115, 97, 103, 101, 73, 68, 62, 73, 68, 45, 109, 97, 110, 111, 45, 52, 52, 51, 53, 54, 45, 49, 52, 55, 52, 50, 56, 49, 57, 53, 54, 57, 48, 56, 45, 56, 45, 49, 48, 55, 60, 47, 115, 99, 104, 58, 77, 101, 115, 115, 97, 103, 101, 73, 68, 62, 32, 32, 32, 32, 32, 32, 32, 32, 32, 60, 110, 101, 116, 119, 111, 114, 107, 73, 112, 62, 49, 51, 51, 46, 49, 54, 56, 46, 49, 46, 49, 54, 60, 47, 110, 101, 116, 119, 111, 114, 107, 73, 112, 62, 32, 32, 32, 32, 32, 32, 32, 32, 32, 60, 105, 115, 83, 117, 99, 99, 101, 115, 115, 62, 102, 97, 108, 115, 101, 60, 47, 105, 115, 83, 117, 99, 99, 101, 115, 115, 62, 32, 32, 32, 32, 32, 32, 32, 32, 32, 60, 115, 116, 97, 116, 117, 115, 62, 115, 117, 99, 99, 115, 115, 60, 47, 115, 116, 97, 116, 117, 115, 62, 32, 32, 32, 32, 32, 32, 60, 47, 115, 99, 104, 58, 105, 110, 118, 111, 107, 101, 82, 101, 115, 112, 111, 110, 115, 101, 62] to java.io.PrintStream@2c68d32d
2016-09-20 17:32:59,888  DEBUG  o.apache.camel.processor.ChoiceProcessor:75    #0 - header{header(AvailableMessageID)} == true matches: true for: Exchange[Message: <sch:invokeResponse xmlns:sch="http://siserver.org/schema">         sch:MessageIDID-mano-44356-1474281956908-8-107/sch:MessageID         <networkIp>133.168.1.16</networkIp>         <isSuccess>false</isSuccess>         <status>succss</status>      /sch:invokeResponse]
2016-09-20 17:32:59,889  DEBUG  o.a.camel.processor.WireTapProcessor:97        >>>> (wiretap) Endpoint[direct://Async-WS-Callback] Exchange[Message: <sch:invokeResponse xmlns:sch="http://siserver.org/schema">         sch:MessageIDID-mano-44356-1474281956908-8-107/sch:MessageID         <networkIp>133.168.1.16</networkIp>         <isSuccess>false</isSuccess>         <status>succss</status>      /sch:invokeResponse]
2016-09-20 17:32:59,891  WARN   o.a.c.component.direct.DirectProducer:54       No consumers available on endpoint: Endpoint[direct://Async-WS-Callback] to process: Exchange[Message: <sch:invokeResponse xmlns:sch="http://siserver.org/schema">         sch:MessageIDID-mano-44356-1474281956908-8-107/sch:MessageID         <networkIp>133.168.1.16</networkIp>         <isSuccess>false</isSuccess>         <status>succss</status>      /sch:invokeResponse]
2016-09-20 17:32:59,907  DEBUG  o.a.camel.processor.DefaultErrorHandler:170    Failed delivery for (MessageId: ID-mano-44356-1474281956908-10-198 on ExchangeId: ID-mano-44356-1474281956908-10-199). On delivery attempt: 0 caught: org.apache.camel.CamelExchangeException: No consumers available on endpoint: Endpoint[direct://Async-WS-Callback]. Exchange[Message: <sch:invokeResponse xmlns:sch="http://siserver.org/schema">         sch:MessageIDID-mano-44356-1474281956908-8-107/sch:MessageID         <networkIp>133.168.1.16</networkIp>         <isSuccess>false</isSuccess>         <status>succss</status>      /sch:invokeResponse]
2016-09-20 17:32:59,912  DEBUG  o.a.c.component.cxf.CxfClientCallback:64       default-workqueue-2 calling handleResponse
2016-09-20 17:32:59,912  DEBUG  org.apache.camel.impl.ConsumerCache:102        <<<< Endpoint[direct://Async-WS-Callback]
2016-09-20 17:32:59,913  DEBUG  org.apache.camel.impl.ConsumerCache:92         Adding to consumer cache with key: Endpoint[direct://Async-WS-Callback] for consumer: PollingConsumer on Endpoint[direct://Async-WS-Callback]
2016-09-20 17:32:59,929  ERROR  o.a.camel.processor.DefaultErrorHandler:215    Failed delivery for (MessageId: ID-mano-44356-1474281956908-10-198 on ExchangeId: ID-mano-44356-1474281956908-10-199). Exhausted after delivery attempt: 1 caught: org.apache.camel.CamelExchangeException: No consumers available on endpoint: Endpoint[direct://Async-WS-Callback]. Exchange[Message: <sch:invokeResponse xmlns:sch="http://siserver.org/schema">         sch:MessageIDID-mano-44356-1474281956908-8-107/sch:MessageID         <networkIp>133.168.1.16</networkIp>         <isSuccess>false</isSuccess>         <status>succss</status>      /sch:invokeResponse]
org.apache.camel.CamelExchangeException: No consumers available on endpoint: Endpoint[direct://Async-WS-Callback]. Exchange[Message: <sch:invokeResponse xmlns:sch="http://siserver.org/schema">         sch:MessageIDID-mano-44356-1474281956908-8-107/sch:MessageID         <networkIp>133.168.1.16</networkIp>         <isSuccess>false</isSuccess>         <status>succss</status>      /sch:invokeResponse]
    at org.apache.camel.component.direct.DirectProducer.process(DirectProducer.java:56) ~[org.apache.camel.camel-core_2.10.4.jar:2.10.4]
    at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:73) [org.apache.camel.camel-core_2.10.4.jar:2.10.4]
    at org.apache.camel.processor.RedeliveryErrorHandler.processErrorHandler(RedeliveryErrorHandler.java:334) [org.apache.camel.camel-core_2.10.4.jar:2.10.4]
    at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:220) [org.apache.camel.camel-core_2.10.4.jar:2.10.4]
    at org.apache.camel.processor.RouteContextProcessor.processNext(RouteContextProcessor.java:46) [org.apache.camel.camel-core_2.10.4.jar:2.10.4]
    at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:90) [org.apache.camel.camel-core_2.10.4.jar:2.10.4]
    at org.apache.camel.processor.UnitOfWorkProcessor.processAsync(UnitOfWorkProcessor.java:150) [org.apache.camel.camel-core_2.10.4.jar:2.10.4]
    at org.apache.camel.processor.UnitOfWorkProcessor.process(UnitOfWorkProcessor.java:117) [org.apache.camel.camel-core_2.10.4.jar:2.10.4]
    at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:99) [org.apache.camel.camel-core_2.10.4.jar:2.10.4]
    at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:86) [org.apache.camel.camel-core_2.10.4.jar:2.10.4]
    at org.apache.camel.processor.WireTapProcessor$1.call(WireTapProcessor.java:98) [org.apache.camel.camel-core_2.10.4.jar:2.10.4]
    at org.apache.camel.processor.WireTapProcessor$1.call(WireTapProcessor.java:94) [org.apache.camel.camel-core_2.10.4.jar:2.10.4]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_45]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]

Regards.

**Comment by aimuke** [comment]
someone may help? thx

**Comment by zimmerml** [comment]
Can you please retry it with the latest (be3a207deb12494b4447f5f4088d26c82ba717c7) version?
Regards

**Comment by aimuke** [comment]
Hi,

This issue happens occasionally. We don't know how to trigger this issue. could you please tell us how did this issue happen and how should we test it?

Regards.

**Comment by miwurster** [comment]
Seems no longer to be an issue, never occurred in the last weeks. Closing this issue for now.
